name: CopperGolemSorter
version: 1.0.0
main: com.coppergolem.sorter.CopperGolemSorterPlugin
api-version: 1.21
author: YourName
description: Enables copper golems to automatically sort items from copper chests into normal chests

commands:
  coppergolem:
    description: Main command for copper golem sorter
    usage: /coppergolem reload|audit
    permission: coppergolem.admin
    aliases: [cg, cgsorter]

permissions:
  coppergolem.admin:
    description: Allows access to admin commands
    default: op
